### ISSUE TITLE
monorepo and inconsistent sub-package versions

### ISSUE THREAD

**Issue by favoyang** [quabug/EntitiesBT#119]
Hi @quabug,

You have a good monorepo setup, but your sub-package versions are inconsistent. i.e. for Git tag `0.21.2`, some package may be still versioned with `0.21.0`. This is not a problem, but it confused openupm build pipelines that not all package versions are matched with the tag version.

Two options
1. Keep all sub-packages versions synced with your Git tag version. This will also send your user a clear signal that whether all packages are synced, but a user may force to do unnecessary updates for packages not get real updated.
1. Create a Git tag for an individual package with a related prefix, and ask openupm-cli to track the Git tag prefix instead. [ReeseUnityDemos](https://github.com/reeseschultz/ReeseUnityDemos) is an example. The sub-package [com.reese.random](https://github.com/openupm/openupm/blob/master/data/packages/com.reese.random.yml) ask our pipelines to track `random` prefix. The author @reeseschultz is creating a tool called https://github.com/reeseschultz/ubump to automate the process.

You can also ignore the issue, and version conflict errors on your openupm page like https://openupm.com/packages/com.quabug.entities-bt.builder.component/.

**Comment by quabug** [comment]
Thank you for mention this issue and provide those options.
I'll config an action to process releases automatically next time.
