### ISSUE TITLE
Failed to run Sample properly

### ISSUE THREAD

**Issue by optimisez00** [quabug/EntitiesBT#138]
I tried to run the sample but log me error and warning. Any idea what the cause and how to fix them? 

![image](https://user-images.githubusercontent.com/61968058/96137899-ca7cfb00-0f2f-11eb-814c-c2c1d8d82144.png)

**Comment by quabug** [comment]
@optimisez00 thank you for reporting this bug.
It's been fixed at the latest version of sample (0.21.9)
