### ISSUE TITLE
Visual Graph Tree Builder Documentation

### ISSUE THREAD

**Issue by sNaticY** [quabug/EntitiesBT#147]
Would be great if we can have a very simple "How to Start" section for the Visual Graph Tree Builder

**Comment by quabug** [comment]
Visual builder is an experimental package depends on [a barely maintained DOTS VS package (DROP)](https://forum.unity.com/threads/dots-visual-scripting-experimental-drop-11.944793/),  and it won't be actively developed as long as DROP still in suspended.
Any usage of visual builder is discouraged, so there won't be any kind of document in my plan.

Anyway, I am considering replace it by [NodeGraphProcessor](https://github.com/alelievr/NodeGraphProcessor) or [Bolt](https://assetstore.unity.com/packages/tools/visual-scripting/bolt-163802).

I will leave this issue "open" until I actually write a new visual graph builder with document.

**Comment by quabug** [comment]
#181
