### ISSUE TITLE
EntitiesBT on OpenUPM

### ISSUE THREAD

**Issue by favoyang** [quabug/EntitiesBT#19]
Hi @quabug ,

Thanks for creating the amazing project. I'm the creator of [OpenUPM](https://openupm.com), a public upm registry with automatic build pipelines that publish new package bundle based on semver git tags. You can read [the announcement](https://www.patreon.com/posts/openupm-beta-is-32544176) to get the basic idea, so far it hosts 80+ packages as of December 2019.

I have added this package: [https://openupm.com/packages/entities-bt/](https://openupm.com/packages/entities-bt/). To make it useful, could you please 
- Make a [GitHub Release](https://github.com/quabug/EntitiesBT/releases) for v0.2.0
- [Optional] consider [adding a badge](https://openupm.com/docs/adding-badge.html).

**Comment by favoyang** [comment]
I've noticed the GitHub releases that being processed correctly:

[![image](https://user-images.githubusercontent.com/125390/71580693-a7b65d00-2b3c-11ea-82c1-0268323d81e2.png)](https://openupm.com/packages/entities-bt/)

Feel free to [add the badge](https://openupm.com/docs/adding-badge.html): [![openupm](https://img.shields.io/npm/v/entities-bt?label=openupm&registry_uri=https://package.openupm.com)](https://openupm.com/packages/entities-bt/)

Thanks for the efforts.

**Comment by quabug** [comment]
Hey @favoyang ,
Your project looks very useful!
I've made release and also add badge into readme.
thank you to notice this
